spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb+srv://yithu:vithu@cluster0.4q4ztau.mongodb.net/?retryWrites=true&w=majority}
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE:Dev}
server.port=${PORT:8080}

spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER
