spring.data.mongodb.uri=mongodb+srv://alokalakruwan_10:XKBFYne1HlePbz0q@clusterfinalproject.bki5ss4.mongodb.net/?retryWrites=true&w=majority
spring.data.mongodb.database=dev

spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER

